version: "3.8"
services:
  php-apache-environment:
    container_name: php-apache
    build:
      dockerfile: Dockerfile
    depends_on:
      - mysql
    volumes:
      - ./src:/var/www/html/
    ports:
      - "80:80"

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo1234
    volumes:
      - ./init_scripts:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    restart: always
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
